// Builds the online demo for GitHub Pages into dist/ — the same screens, with no server.
// js/browser-server.js (static/browser-server.js + src/store.js) answers the pages' /api calls and live updates
// inside the browser. Orders are kept in that browser, and its open tabs update each other.
//
//   npm run build:static
//   PAGES_URL=https://<user>.github.io/<repo> npm run build:static    (default below)

const fs = require('fs');
const os = require('os');
const path = require('path');
const QRCode = require('qrcode');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'dist');
const PAGES_URL = (process.env.PAGES_URL || 'https://nargizmammadli.github.io/borani-table-ordering').replace(/\/$/, '');
const BASE = new URL(PAGES_URL).pathname.replace(/\/$/, '');
const MAX_TABLES = 200; // LIMITS.maxTables in src/store.js
const PINS = { kitchen: process.env.KITCHEN_PIN || '1111', reception: process.env.RECEPTION_PIN || '2222' };

// Table codes come from src/store.js itself, signed with a fixed key so demo links and QR codes never change.
process.env.SESSION_SECRET = 'borani-static-demo';
process.env.DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'borani-static-'));
process.env.TABLE_COUNT = String(MAX_TABLES);
const { sign } = require('../src/secret');
const store = require('../src/store');

const tables = store.tableCodes();
const tableUrl = (t) => `${PAGES_URL}/t/${t.table}/${t.code}/`; // same format as in static/browser-server.js

// Root-relative addresses ("/css/…", "/reception") get the Pages sub-path; "/api/…" is answered in the browser.
const withBase = (text) =>
  text.replace(/(["'`(])\/(css|js|img)\//g, `$1${BASE}/$2/`).replace(/(["'`])\/(reception|kitchen|qr)(["'`])/g, `$1${BASE}/$2/$3`);

function replaceOnce(text, from, to, where) {
  if (!text.includes(from)) throw new Error(`${where} has changed; update scripts/build-static.js (looking for: ${from})`);
  return text.replace(from, () => to);
}

function write(file, content) {
  const target = path.join(OUT, file);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content);
}

function copyAssets(dir) {
  for (const entry of fs.readdirSync(path.join(ROOT, 'public', dir), { withFileTypes: true })) {
    const rel = path.join(dir, entry.name);
    if (entry.isDirectory()) copyAssets(rel);
    else if (/\.(js|css)$/.test(entry.name)) write(rel, withBase(fs.readFileSync(path.join(ROOT, 'public', rel), 'utf8')));
    else {
      fs.mkdirSync(path.join(OUT, dir), { recursive: true });
      fs.copyFileSync(path.join(ROOT, 'public', rel), path.join(OUT, rel));
    }
  }
}

// The socket.io client is replaced by the in-browser server, which must load before the page scripts.
function page(file) {
  let html = fs.readFileSync(path.join(ROOT, 'public', file), 'utf8');
  const serverScript = `<script src="${BASE}/js/browser-server.js"></script>`;
  const socketScript = '<script src="/socket.io/socket.io.js"></script>';
  if (html.includes(socketScript)) html = html.replace(socketScript, () => serverScript);
  else html = replaceOnce(html, '<script src="/js/i18n.js"></script>', `${serverScript}\n    <script src="/js/i18n.js"></script>`, file);
  return withBase(html);
}

function browserServer() {
  const menu = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'menu.json'), 'utf8').replace(/"\/img\//g, `"${BASE}/img/`));
  const build = {
    base: BASE,
    pagesUrl: PAGES_URL,
    pins: PINS,
    menu,
    signatures: Object.fromEntries(tables.map((t) => [`table:${t.table}`, sign(`table:${t.table}`)])),
  };
  const storeSource = fs.readFileSync(path.join(ROOT, 'src', 'store.js'), 'utf8');
  const serverSource = fs.readFileSync(path.join(ROOT, 'static', 'browser-server.js'), 'utf8');
  return `// Generated by scripts/build-static.js from static/browser-server.js and src/store.js. Do not edit.
(function () {
const BUILD = ${JSON.stringify(build)};

function createStore(shims) {
  const module = { exports: {} };
  const require = (name) => {
    if (!Object.prototype.hasOwnProperty.call(shims, name)) throw new Error('static demo: no browser version of "' + name + '"');
    return shims[name];
  };
  // src/store.js, unchanged. Saves run at once instead of after 200 ms, so other tabs read the change straight away.
  (function (require, module, exports, __dirname, process, setTimeout, clearTimeout) {
${storeSource}
  })(require, module, module.exports, '/src', { env: {} }, (fn) => (fn(), 0), () => {});
  return module.exports;
}

${serverSource}
})();
`;
}

async function main() {
  fs.rmSync(OUT, { recursive: true, force: true });
  for (const dir of ['css', 'img', 'js']) copyAssets(dir);

  write(
    'js/guest.js',
    replaceOnce(
      fs.readFileSync(path.join(OUT, 'js', 'guest.js'), 'utf8'),
      "location.pathname.split('/')",
      `location.pathname.slice(${JSON.stringify(BASE)}.length).split('/')`,
      'public/js/guest.js'
    )
  );
  write('js/browser-server.js', browserServer());

  let launcher = page('demo.html');
  launcher = replaceOnce(
    launcher,
    'Demo launcher. Open the three screens, then scan a table QR code with a phone that is on the same Wi-Fi as this computer.',
    'Online demo that runs entirely in your browser. Open the screens in separate tabs and they update each other live.',
    'public/demo.html'
  );
  launcher = replaceOnce(
    launcher,
    '`Phones open: ${data.base}  —  if a phone cannot open it, make sure it is on the same Wi-Fi and allow Node.js through the Windows firewall.`',
    "'Orders are saved in this browser only, so open the table, reception and kitchen in tabs of the same browser. A phone that scans a code gets its own separate demo.'",
    'public/demo.html'
  );
  launcher = replaceOnce(launcher, 'Scan table 1 with a phone (or click “open here”)', 'Click “Open here” under table 1', 'public/demo.html');
  write('index.html', launcher);

  write('reception/index.html', page('reception.html'));
  write('kitchen/index.html', page('kitchen.html'));
  write('qr/index.html', page('qr.html'));
  const menuPage = page('menu.html');
  for (const t of tables) write(`t/${t.table}/${t.code}/index.html`, menuPage);

  for (const t of tables) {
    write(`img/qr/${t.table}.svg`, await QRCode.toString(tableUrl(t), { type: 'svg', margin: 1, errorCorrectionLevel: 'M' }));
  }

  write(
    '404.html',
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Not found — Boranı</title>
    <link rel="icon" href="${BASE}/img/logo.jpg" />
    <link rel="stylesheet" href="${BASE}/css/base.css" />
  </head>
  <body>
    <main style="max-width: 480px; margin: 80px auto; padding: 0 16px; text-align: center">
      <img src="${BASE}/img/logo.jpg" alt="" width="82" height="82" style="border-radius: 50%" />
      <h1>Page not found</h1>
      <p><a class="btn btn-primary" href="${BASE}/">Open the demo</a></p>
    </main>
  </body>
</html>
`
  );
  write('.nojekyll', ''); // publish files as they are

  // Anything still pointing at the site root would 404 on GitHub Pages.
  const leftovers = [];
  const scan = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const file = path.join(dir, entry.name);
      if (entry.isDirectory()) scan(file);
      else if (/\.(html|js|css)$/.test(entry.name) && /["'`(]\/(css|js|img|socket\.io|reception|kitchen|qr)\b/.test(fs.readFileSync(file, 'utf8')))
        leftovers.push(path.relative(OUT, file));
    }
  };
  scan(OUT);
  if (leftovers.length) throw new Error(`root-relative addresses left in: ${[...new Set(leftovers)].join(', ')}`);

  fs.rmSync(process.env.DATA_DIR, { recursive: true, force: true });
  console.log(`Static demo written to dist/ for ${PAGES_URL}/ (${tables.length} table pages)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
